import express from "express";
import { homeController } from "../controllers/home.controller";
import userRouter from "./users";
import { authMiddleware } from "../middlewares/auth.middleware";
import { uploadController } from "../controllers/upload.controller";
import { upload } from "../utils/multer";
const router = express.Router();
router.get("/", homeController.index);
router.use("/users", authMiddleware, userRouter);
router.post("/uploads", upload.single("image"), uploadController.upload);
export default router;
