import express from "express";
import { validate } from "../middlewares/validate.middleware";
import { createProductSchema } from "../validators/product.validator";
import { productController } from "../controllers/product.controller";
import { authMiddleware } from "../middlewares/auth.middleware";
const router = express.Router();
router.get('/products', productController.findAll);
router.post('/products', authMiddleware, validate(createProductSchema), productController.create);
router.get('/products/:id', productController.find);
export default router;